services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: viniciusbrun/shared-notes:frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"  # Map FRONTEND_PORT or 3000 on host to container port 80 (Nginx)  
    environment:
      - PORT=${FRONTEND_PORT:-3000}  # Default to 3000 if not set
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: viniciusbrun/shared-notes:backend
    ports:
      - "${BACKEND_PORT:-5000}:5000"  # Default to 5000 if BACKEND_PORT is not set
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT:-5000}  # Default to 5000 if not set
    depends_on:
      - frontend
    restart: always
