services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"  # Default to 3000 for Vite dev server
    environment:
      - NODE_ENV=${FRONTEND_NODE_ENV:-development}  # Default to 'development'
      - PORT=${FRONTEND_PORT:-3000}  # Default to 3000 if not set
      - CHOKIDAR_USEPOLLING=true  # Enable polling for live reload in Docker
    volumes:
      - ./frontend:/app  # Mounts local frontend code to container
      - /app/node_modules  # Avoids mounting node_modules to prevent conflicts
    command: ["npm", "run", "dev"]  # Starts Vite in dev mode
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "${BACKEND_PORT:-5000}:5000"  # Default to 5000 if BACKEND_PORT is not set
    environment:
      - NODE_ENV=${BACKEND_NODE_ENV:-development}  # Default to 'development'
      - PORT=${BACKEND_PORT:-5000}  # Default to 5000 if not set
    volumes:
      - ./backend:/app  # Mounts local backend code to container
      - /app/node_modules  # Avoids mounting node_modules to prevent conflicts
    command: ["npm", "run", "dev"]  # Starts backend in dev mode with live reload
