name: Deploy to VM

on:
  workflow_run:
    workflows: ["Docker Build"]  # Name of the triggering workflow
    types:
      - completed  # Run only when "Docker Build" workflow is completed successfully

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  DEPLOY_HOST: "sharednotes.app"
  DEPLOY_USER: "ubuntu"
  REPO_PATH: "/home/ubuntu/shared-notes"
  DOCKER_COMPOSE_FILE: "docker-compose.yml"
  IMAGE_NAME: "viniciusbrun/shared-notes"

jobs:
  deploy:
    if: ${{ github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Set VERSION for Deployment
        id: set-version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "0.0.0")
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Setup SSH with Passphrase
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Setting up SSH directory and permissions..."
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Adding deploy host to known_hosts..."
          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          # Set up ssh-agent with a fixed socket path and add the key
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection to ensure configuration is correct..."
          ssh -v -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_HOST "echo 'SSH connection successful'"

      - name: Pull Docker Image and Deploy
        run: |
          echo "Deploying Docker container on remote server..."
          ssh -v -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_HOST << EOF
            set -e  # Exit if any command fails
            cd $REPO_PATH

            echo "Pulling latest Docker image: $IMAGE_NAME:$VERSION"
            docker pull $IMAGE_NAME:$VERSION

            echo "Stopping current Docker Compose services..."
            docker-compose -f $DOCKER_COMPOSE_FILE down || echo "No containers to stop, skipping..."

            echo "Starting updated Docker Compose services..."
            docker-compose -f $DOCKER_COMPOSE_FILE up -d || exit 1
            echo "Deployment complete."
          EOF

      - name: Clean Up Local SSH Keys
        if: always()
        run: |
          echo "Cleaning up SSH keys and known_hosts for security..."
          rm -f ~/.ssh/id_rsa
          rm -f ~/.ssh_askpass
          rm -f ~/.ssh/known_hosts
